Class cjs.interopway.rest.bo.DeleteResponse Extends (%Persistent, cjs.interopway.rest.bo.BaseResponse)
{

Storage Default
{
<Data name="DeleteResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interopw6BF.DeleteResponseD</DataLocation>
<DefaultData>DeleteResponseDefaultData</DefaultData>
<IdLocation>^cjs.interopw6BF.DeleteResponseD</IdLocation>
<IndexLocation>^cjs.interopw6BF.DeleteResponseI</IndexLocation>
<StreamLocation>^cjs.interopw6BF.DeleteResponseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
