Class cjs.interopway.rest.bo.DeleteRequest Extends (%Persistent, cjs.interopway.rest.bo.BaseRequest)
{

Parameter RESPONSECLASSNAME As STRING = "cjs.interopway.rest.bo.DeleteResponse";

Storage Default
{
<Data name="DeleteRequestDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>RequestDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interopwa6BF.DeleteRequestD</DataLocation>
<DefaultData>DeleteRequestDefaultData</DefaultData>
<IdLocation>^cjs.interopwa6BF.DeleteRequestD</IdLocation>
<IndexLocation>^cjs.interopwa6BF.DeleteRequestI</IndexLocation>
<StreamLocation>^cjs.interopwa6BF.DeleteRequestS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
