Class cjs.interopway.rest.bo.GetResponse Extends (%Persistent, cjs.interopway.rest.bo.BaseResponse)
{

/// Subclass responsablity
Method DoSpecifAction(pArgs...)
{
	return
}

Storage Default
{
<Data name="GetResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interopway6BF.GetResponseD</DataLocation>
<DefaultData>GetResponseDefaultData</DefaultData>
<IdLocation>^cjs.interopway6BF.GetResponseD</IdLocation>
<IndexLocation>^cjs.interopway6BF.GetResponseI</IndexLocation>
<StreamLocation>^cjs.interopway6BF.GetResponseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
