Class cjs.interopway.rest.bo.PatchRequest Extends (%Persistent, cjs.interopway.rest.bo.BaseRequest)
{

Parameter RESPONSECLASSNAME As STRING = "cjs.interopway.rest.bo.PatchResponse";

Storage Default
{
<Data name="PatchRequestDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>RequestDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interopway6BF.PatchRequestD</DataLocation>
<DefaultData>PatchRequestDefaultData</DefaultData>
<IdLocation>^cjs.interopway6BF.PatchRequestD</IdLocation>
<IndexLocation>^cjs.interopway6BF.PatchRequestI</IndexLocation>
<StreamLocation>^cjs.interopway6BF.PatchRequestS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
