Class cjs.interopway.rest.bo.PatchResponse Extends (%Persistent, cjs.interopway.rest.bo.BaseResponse)
{

Storage Default
{
<Data name="PatchResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interopwa6BF.PatchResponseD</DataLocation>
<DefaultData>PatchResponseDefaultData</DefaultData>
<IdLocation>^cjs.interopwa6BF.PatchResponseD</IdLocation>
<IndexLocation>^cjs.interopwa6BF.PatchResponseI</IndexLocation>
<StreamLocation>^cjs.interopwa6BF.PatchResponseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
