Class cjs.interopway.rest.bo.PostResponse Extends (%Persistent, cjs.interopway.rest.bo.BaseResponse)
{

Storage Default
{
<Data name="PostResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interopway6BF.PostResponseD</DataLocation>
<DefaultData>PostResponseDefaultData</DefaultData>
<IdLocation>^cjs.interopway6BF.PostResponseD</IdLocation>
<IndexLocation>^cjs.interopway6BF.PostResponseI</IndexLocation>
<StreamLocation>^cjs.interopway6BF.PostResponseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
