Class cjs.interopway.rest.bo.PutRequest Extends (%Persistent, cjs.interopway.rest.bo.BaseRequest)
{

Parameter RESPONSECLASSNAME As STRING = "cjs.interopway.rest.bo.PutResponse";

Storage Default
{
<Data name="PutRequestDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>RequestDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interopway.r6BF.PutRequestD</DataLocation>
<DefaultData>PutRequestDefaultData</DefaultData>
<IdLocation>^cjs.interopway.r6BF.PutRequestD</IdLocation>
<IndexLocation>^cjs.interopway.r6BF.PutRequestI</IndexLocation>
<StreamLocation>^cjs.interopway.r6BF.PutRequestS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
