Class cjs.interopway.rest.bo.PutResponse Extends (%Persistent, cjs.interopway.rest.bo.BaseResponse)
{

Storage Default
{
<Data name="PutResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interopway6BF.PutResponseD</DataLocation>
<DefaultData>PutResponseDefaultData</DefaultData>
<IdLocation>^cjs.interopway6BF.PutResponseD</IdLocation>
<IndexLocation>^cjs.interopway6BF.PutResponseI</IndexLocation>
<StreamLocation>^cjs.interopway6BF.PutResponseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
