/// <p style='text-align: justify;'>
/// <b>2020-06-10 - Cristiano José da Silva</b><br/>
/// Response for SELECT Statments.
/// </p>
Class cjs.interopway.xdbc.bo.QueryResponse Extends (%Persistent, cjs.interopway.xdbc.bo.BaseResponse)
{

Storage Default
{
<Data name="QueryResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Snapshots</Value>
</Value>
</Data>
<DataLocation>^cjs.interopw60ED.QueryResponseD</DataLocation>
<DefaultData>QueryResponseDefaultData</DefaultData>
<IdLocation>^cjs.interopw60ED.QueryResponseD</IdLocation>
<IndexLocation>^cjs.interopw60ED.QueryResponseI</IndexLocation>
<StreamLocation>^cjs.interopw60ED.QueryResponseS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}
